#!/bin/bash
# 
# Dzen2 App Launcher
# -tw = Width of titlebar, -w = Width of slavewindow,
# -l = length of slavewindow. Remember to adjust -l accordingly when adding 
# apps.  
#
# Needed Applications:

AP1=urxvt
AP2=google-chrome-stable
AP3=thunar
AP4=
AP5=

# Deco:

DC1=3x17
DC2=8x8
DC3=8x3
DC4=3x3

#FONT

FONT="-*-dina-medium-r-*-*-15-*-*-*-*-*-iso8859-1"

# Colors:

FG1=#9ab8c2
FG2=#f57900
FG3=#D9A509

# Icons:

ICM=/home/jacob/.xmonad/dzen2/arch.xbm
IC1=/home/jacob/.xmonad/dzen2/note.xbm
IC2=/home/jacob/.xmonad/dzen2/note.xbm
IC3=/home/jacob/.xmonad/dzen2/note.xbm
IC4=/home/jacob/.xmonad/dzen2/note.xbm

# Text parsed to Dzen2

(echo "^fg(${FG2})^i(${ICM})"; echo -e "^fg(${FG1})\
^r(${DC1})^r(${DC2})^r(${DC3}) ^fg(${FG3})^i(${IC1})^fg(${FG1}) ${AP1} ^pa(106)^r(${DC3})^r(${DC2})^r(${DC1})\
\n^r(${DC1})^r(${DC2})^r(${DC3}) ^fg(${FG3})^i(${IC2})^fg(${FG1}) ${AP2} ^pa(106)^r(${DC3})^r(${DC2})^r(${DC1})\
\n^r(${DC1})^r(${DC2})^r(${DC3}) ^fg(${FG3})^i(${IC3})^fg(${FG1}) ${AP3} ^pa(106)^r(${DC3})^r(${DC2})^r(${DC1})\
\n^r(${DC1})^r(${DC2})^r(${DC3}) ^fg(${FG3})^i(${IC4})^fg(${FG1}) ${AP4} ^pa(106)^r(${DC3})^r(${DC2})^r(${DC1})")\
| (dzen2 -y '0' -fn "$FONT" -bg '#43464f' -fg '#9ab8c2' -l 4 -tw 30 -w 125 -m -p -e 'entertitle=uncollapse;leaveslave=collapse;button1=menuexec')
