# ~/.mpd/mpd.conf - mpd configuration file
# ~/.ncmpcpp/config
#   mpd_host = "localhost"
#   mpd_port = "6600"

music_directory     "~/music"
playlist_directory  "~/.mpd/playlists"
db_file             "~/.mpd/database"
log_file            "~/.mpd/log"
pid_file            "~/.mpd/pid"
state_file          "~/.mpd/state"
sticker_file        "~/.mpd/sticker.sql"



# General music daemon options ################################################
user            "mpd"
# user            "jacob"
bind_to_address "localhost"
port            "6600"

# listen: bind to '0.0.0.0:6600' failed: Address already in use (continuing anyway, because binding to '[::]:6600' succeeded)
# bind_to_address "any"
# bind_to_address "127.0.0.1"
# bind_to_address "/var/run/mpd/socket"
# log_level      "default"

#uncomment here and set restore_pause parameter to yes if you want MPD does not start automatically the latest playlist at startup
#restore_paused "no"

# metadata_to_use "artist,album,title,track,name,genre,date,composer,performer,disc"
# auto_update     "yes"
# gapless_mp3_playback "yes"

#Uncomment if you allow MPD to manage volume by software
#mixer_type   "software" 

# audio_output {
#         type            "pulse"
#         name            "pulse audio"
# }
