#!/bin/bash
# ------------------------------------------------------------------
#     Scripts/mailcount
#     Description: Script for checking the number of unread mails
#     Author: Alex Sánchez <kniren@gmail.com>
# ------------------------------------------------------------------

MAILDIR="$HOME/.mail/aau/INBOX/new"
NUMBER=`find $MAILDIR -type f | wc -l`
#ICON='^i(/home/jacob/.xmonad/dzen2/img/mail.xbm)'


MAILDIR2="$HOME/.mail/jacobgmail/INBOX/new"
NUMBER2=`find $MAILDIR2 -type f | wc -l`
ICON2='^i(/home/jacob/.xmonad/dzen2/img/mail.xbm)'

echo "$NUMBER  $ICON2 $NUMBER2"
