#!/bin/bash
# 
# Dzen2 App Launcher
# -tw = Width of titlebar, -w = Width of slavewindow,
# -l = length of slavewindow. Remember to adjust -l accordingly when adding apps.  

# Applications
AP1=urxvt
AP2=firefox
AP3=thunar
AP4=pavucontrol

#FONT
# FONT="-*-terminus-medium-r-*-*-16-*-*-*-*-*-*-*"
FONT="-*-ubuntu-medium-r-*-*-20-*-*-*-*-*-*-*"

# Colors 
BLACK=#282828
GREEN=#5faf5f
BROWN=#fdf6e3
FG1=$GREEN
FG2=$GREEN
FG3=$GREEN
# # Light theme
# FG=$GREEN
# BG=$BROWN
# Dark theme
FG=$GREEN
BG=$BLACK

# Icons
ICM=~/.xmonad/dzen2/img/arch.xbm
IC1=~/.xmonad/dzen2/img/term.xbm
IC2=~/.xmonad/dzen2/img/fox.xbm
IC3=~/.xmonad/dzen2/img/docs.xbm
IC4=~/.xmonad/dzen2/img/phones.xbm

# Text parsed to Dzen2
(echo "^fg(${FG2})^i(${ICM})"; echo -e "^fg(${FG1})\
  ^fg(${FG3})^i(${IC1})^fg(${FG1}) ${AP1}   \n\
  ^fg(${FG3})^i(${IC2})^fg(${FG1}) ${AP2}   \n\
  ^fg(${FG3})^i(${IC3})^fg(${FG1}) ${AP3}   \n\
  ^fg(${FG3})^i(${IC4})^fg(${FG1}) ${AP4} ")\
| (dzen2 -h '20' -fn "$FONT" -bg $BG -fg $FG -l 4 -tw 30 -w 150 -m -p -e 'entertitle=uncollapse;button1=menuexec;leaveslave=collapse;button1=menuexec')
